### ISSUE TITLE
Error when i try to import product

### ISSUE THREAD

**Issue by Fishburne** [rex2630/codeswholesale-for-woocommerce#5]
I get this with or without activated filters:

Client error: `POST https://api.codeswholesale.com/v2/imports` resulted in a `400 Bad Request` response: {"status":400,"code":12005,"message":"Territory has not been found","developerMessage":"Territory has not been found","m (truncated...)

**Comment by rex2630** [comment]
DUPLICATE ISSUE: https://github.com/rex2630/codeswholesale-for-woocommerce/issues/1

**Comment by Fishburne** [comment]
The error message is not really the same.
