### ISSUE TITLE
Issue after plugin activation

### ISSUE THREAD

**Issue by pjindras** [rex2630/codeswholesale-for-woocommerce#7]
Hello, after plugin activation, my wp went down, this is the error, which i have recieved by email.

Podrobnosti chyby
=================
Na řádku č. 55 v souboru /data/web/virtuals/257900/virtual/www/domains/waresoft.eu/wp-content/plugins/codeswholesale-for-woocommerce-master/vendor/codeswholesale/cw-extension-framework/src/Connection/Connection.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught Error: Class 'CodesWholesale\ClientBuilder' not found in /data/web/virtuals/257900/virtual/www/domains/waresoft.eu/wp-content/plugins/codeswholesale-for-woocommerce-master/vendor/codeswholesale/cw-extension-framework/src/Connection/Connection.php:55
Stack trace:
#0 /data/web/virtuals/257900/virtual/www/domains/waresoft.eu/wp-content/plugins/codeswholesale-for-woocommerce-master/codeswholesale.php(366): CodesWholesaleFramework\Connection\Connection::getConnection(Array)
#1 /data/web/virtuals/257900/virtual/www/domains/waresoft.eu/wp-content/plugins/codeswholesale-for-woocommerce-master/codeswholesale.php(120): CodesWholesale->configure_cw_client()
#2 /data/web/virtuals/257900/virtual/www/domains/waresoft.eu/wp-content/plugins/codeswholesale-for-woocommerce-master/codeswholesale.php(305): CodesWholesale->__construct()
#3 /data/web/virtuals/257900/virtual/www/domains/waresoft.eu/wp-content/plugins/codeswholesale-for-woocommerce-master/codeswholesale.php(459): CodesWholesale::instance()
#4 /data/web/virt

**Comment by rex2630** [comment]
Hello, it doesnt make sense if u have newest PHP version, woocomerce, wordpress and everything. Maybe you just downloaded wrong file and dont know how to properly download release. Download this: https://github.com/rex2630/codeswholesale-for-woocommerce/releases/tag/2.6.8

**Comment by rex2630** [comment]
This issue doesnt exist, it has been tested several times, closing this issue...
